name: Generar reportes desde Supabase

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generar-reportes:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Instalar PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Crear carpeta de reportes
        run: mkdir -p reports

      - name: Ejecutar consultas SQL y guardar como CSV
        env:
          DB_URI: ${{ secrets.SUPABASE_DB_URI }}
        run: |
          mkdir -p reports
          for f in sql/*.sql; do
            nombre=$(basename "$f" .sql)
            echo "Procesando $nombre.sql..."
            psql "${DB_URI}?sslmode=require" \
              --csv \
              -f "$f" > "reports/$nombre.csv"
          done

      - name: Commit y push de reportes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Actualizar reportes CSV"
          add: "reports/*.csv"
          author_name: "GitHub Action"
          author_email: "action@github.com"

  publicar-gh-pages:
    needs: generar-reportes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
