name: Run SQL and Publish Reports

on:
  push:
    paths:
      - "sql/**"
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run SQL scripts and export CSVs
        run: |
          DB_URI="postgresql://postgres:admin@db.zpmjgwsnoetnxowccjmx.supabase.co:5432/postgres"
          export PGPASSWORD=admin
          export PGHOST=db.zpmjgwsnoetnxowccjmx.supabase.co
          export PGPORT=5432
          export PGUSER=postgres
          export PGDATABASE=postgres

          for sqlfile in sql/*.sql; do
            csvfile="reports/$(basename "${sqlfile}" .sql).csv"
            echo "Ejecutando $sqlfile y guardando en $csvfile"
            psql -f "$sqlfile" -A -F"," --no-align -o "$csvfile"
          done

      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
