name: Run SQL and Publish Reports

on:
  push:
    paths:
      - 'sql/**'
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run SQL scripts and export CSVs
        env:
          DB_URI: ${{ secrets.SUPABASE_DB_URI }}
        run: |
          for sqlfile in sql/*.sql; do
            csvfile="reports/$(basename "${sqlfile}" .sql).csv"
            echo "Ejecutando $sqlfile y guardando en $csvfile"
            PGPASSWORD=$(echo $DB_URI | sed -n 's#.*postgres:\([^@]*\)@.*#\1#p') \
            psql "$DB_URI" -f "$sqlfile" -A -F"," --no-align -o "$csvfile"
          done

      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
