name: Generar reporte Supabase

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ejecutar scripts SQL
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.ANON_KEY }}
        run: |
          export PGSSLMODE=require
          export PGPASSWORD=$SUPABASE_ANON_KEY
          for f in sql/*.sql; do
            echo "======== Resultado para $f ========"
            psql -h "$(echo $SUPABASE_URL | awk -F[/:] '{print $4}')" \
                -U "$SUPABASE_ANON_KEY" \
                -d "$(echo $SUPABASE_URL | awk -F/ '{print $NF}')" \
                -c "\i $f" \
                --csv | tee "reports/$(basename "$f" .sql).csv"
          done

      - name: Commit y push reporte
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Actualizar reportes"
          add: "reports/*.csv"

  deploy-pages:
    needs: run-sql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
